# Generated by Django 4.1.7 on 2023-03-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_features_feeding_finch_strength'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='features',
            name='characteristic',
            field=models.CharField(choices=[('Feathers', 'Feathers'), ('High metabolism', 'High metabolism'), ('A four-chambered heart', 'A four-chambered heart'), ('A beak with no teeth', 'A beak with no teeth'), ('A lightweight but strong skeleton', 'A lightweight but strong skeleton'), ('Production of hard-shelled egg', 'Production of hard-shelled egg')], max_length=100),
        ),
        migrations.AlterField(
            model_name='features',
            name='strength',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
    ]
